syntax = "proto3";
package task;
option go_package = "github.com/paytelenko/project-protos/proto/task";

// Сущность задача
message Task {
  uint32 id      = 1;
  uint32 user_id = 2;
  string title   = 3;
  bool is_done   = 4;
}

message CreateTaskRequest {
  uint32 user_id = 1; 
  string title = 2;
}
message CreateTaskResponse {
  Task task = 1;
}

message GetTaskRequest {
  uint32 id = 1;
}

message UpdateTaskRequest {
    uint32 id = 1;
    string title = 2;
    bool is_done = 3;
}
message UpdateTaskResponse {
    Task task = 1;
}

message DeleteTaskRequest{
    uint32 id = 1;
}
message DeleteTaskResponse {}

message ListTasksRequest {
    //пустой запрос
}
message ListTasksResponse {
    repeated Task tasks = 1;
}

message ListTasksByUserRequest {
  uint32 user_id = 1;
}

service TaskService {
  rpc CreateTask (CreateTaskRequest) returns (CreateTaskResponse);
  rpc GetTask    (GetTaskRequest)    returns (Task);
  rpc UpdateTask (UpdateTaskRequest) returns (UpdateTaskResponse);
  rpc DeleteTask (DeleteTaskRequest) returns (DeleteTaskResponse);
  rpc ListTasks (ListTasksRequest) returns (ListTasksResponse);
  rpc ListTasksByUser (ListTasksByUserRequest) returns (ListTasksResponse);
}